### PR TITLE
v3.7.2 Fix the rendering issue with MotionStreak + RigidBody2D on native platforms

### LINKED ISSUE #14300: [v3.7.0] (Regression) MotionStreak with RigidBody2D does not move correctly on Android
### Cocos Creator version

3.7.0, 3.6.3

### System information

Windows 10 Editor

### Issue description

I have a node with a MotionStreak and RigidBody2D components. When I try to move the node it does not render properly on Android devices (seems like it has wrong position and it goes offscreen).
This is the code for the demo:
```
export class Movable extends Component {
    private time: number = 0;
    private direction: number = 1;
    private pos: Vec3 = new Vec3();

    update(deltaTime: number) {
        this.time += deltaTime;
        if (this.time > 3) {
            this.time = 0;
            this.direction *= -1;
        }
        this.node.getPosition(this.pos);
        this.node.setPosition(this.pos.x, this.pos.y + this.direction * 80 * deltaTime, 0);
    }
}
```
This is how it looks when this demo is running in a browser (which is correct):

https://user-images.githubusercontent.com/82378750/219465509-6ea2f380-fbbf-460b-9b72-9efebaf834a4.mp4

But running the demo on Android devices the motionstreak does not appear and the screen is plain black.

This issue was not present in v3.5.2.

### Relevant error log output

_No response_

### Steps to reproduce

Run the attached demo project on Android to see the issue.

### Minimal reproduction project

[Demo2D.zip](https://github.com/cocos/cocos-engine/files/10759706/Demo2D.zip)

### PR DESCRIPTION
**Pull request by mrtzd**
Re: # This pr fixes #14300 and #12992. 

### Changelog

* Fix the issue with MotionStreak plus RigidBody2D not rendering correctly on native platforms

-------

### Continuous Integration

This pull request:

* [ ] needs automatic test cases check.
  > Manual trigger with `@cocos-robot run test cases` afterward.
* [x] does not change any runtime related code or build configuration
  > If any reviewer thinks the CI checks are needed, please uncheck this option, then close and reopen the issue.

-------

### Compatibility Check

This pull request:

* [ ] changes public API, and have ensured backward compatibility with [deprecated features](https://github.com/cocos/cocos-engine/blob/v3.5.0/docs/contribution/deprecated-features.md).
* [ ] affects platform compatibility, e.g. system version, browser version, platform sdk version, platform toolchain, language version, hardware compatibility etc.
* [ ] affects file structure of the build package or build configuration which requires user project upgrade.
* [ ] **introduces breaking changes**, please list all changes, affected features and the scope of violation.

### CODE REVIEW

**Comment by mrtzd** [comment]
@minggo I can't ask for a review but I'd really like to see this get merged for the v3.7.2 release, thanks!

**Comment by minggo** [comment]
@mrtzd thanks for your contribution. We will review it ASAP.

**Comment by SantyWang** [comment]
Thanks for the contribution, I think the previous code is very strange, we will check it out and try to fix it in 3.7.2

**Comment by SantyWang** [comment]
```
comp.node.hasChangedFlags = 0;
```
is INCORRECT, should not be invoked anywhere anytime.

**Comment by mrtzd** [comment]
> ```
> comp.node.hasChangedFlags = 0;
> ```
> 
> is INCORRECT, should not be invoked anywhere anytime.

Yeah since I'm not very familiar with this codebase I didn't know why this line was there too. I removed the whole 'if' block and the code seems to be working fine with my testing although I'm not sure if this is the proper solution.

**Comment by SantyWang** [comment]
> Yeah since I'm not very familiar with this codebase I didn't know why this line was there too. I removed the whole 'if' block and the code seems to be working fine with my testing although I'm not sure if this is the proper solution.

Yeah, I see. Thanks, we will figure it out.

**Review by LinYunMo — COMMENTED** [review]
Thank you for your PR. @mrtzd 

Regarding this issue, **the strange code here is a dirty hack**, due to the special nature of this MotionStreak component, we need to perform world coordinate transformations at the component level, so at the cpp level we want to **avoid repeated world coordinate transformations**, it will cause rendering position exceptions, limited by the current design, we don't have an explicit tag to handle this behavior, so we use the hasChangeFlags to forcibly prevent updates.

Regarding physics, since RigidBody2D have to use hasChangedFlags for position updates, this hack is **moved to after physics uses this tag**, so the problem is avoided.

We will make structural changes in a later version to ensure a more logical flow.

Thanks again for the PR!

File: cocos/particle-2d/motion-streak-2d-assembler.ts [hunk 1]
```diff
@@ -244,6 +243,10 @@ export const MotionStreakAssembler: IAssembler = {
     },
 
     updateRenderData (comp: MotionStreak) {
+        if (JSB) {
```
Comment (LinYunMo) [inline cocos/particle-2d/motion-streak-2d-assembler.ts:244]: Could you please add some comments to this code so that it can be identified for subsequent maintenance: like this

```
// A dirty hack
// The world matrix was updated in advance and needs to be avoided at the cpp level
// Need a flag to explicitly not update the world transform to solve this problem
```

Thanks a lot

**Review by LinYunMo — CHANGES_REQUESTED** [review]

File: cocos/particle-2d/motion-streak-2d-assembler.ts (hunk 1 above)
Comment (mrtzd) [reply cocos/particle-2d/motion-streak-2d-assembler.ts:244]: Thanks for the explanation. I added the comments.

**Review by SantyWang — APPROVED** [review]
