### PR TITLE
fixed #18374: 2D Node with MotionStreak and Rigidbody has wrong offset

### LINKED ISSUE #18374: 2D Node with MotionStreak and Rigidbody has wrong offset
Reported at https://forum.cocos.org/t/topic/165730
This bug happens from v3.8.4.
We fixed an issue https://github.com/cocos/cocos-engine/pull/17555 
But MotionStreak assembler has a dirty flag hack in https://github.com/cocos/cocos-engine/blob/3.8.5/cocos/particle-2d/motion-streak-2d-assembler.ts#L248 which I didn't know.

### PR DESCRIPTION
**Pull request by dumganhar**
Re: #18374

### Changelog

*

-------

### Continuous Integration

This pull request:

* [ ] needs automatic test cases check.
  > Manual trigger with `@cocos-robot run test cases` afterward.
* [ ] does not change any runtime related code or build configuration
  > If any reviewer thinks the CI checks are needed, please uncheck this option, then close and reopen the issue.

-------

### Compatibility Check

This pull request:

* [ ] changes public API, and have ensured backward compatibility with [deprecated features](https://github.com/cocos/cocos-engine/blob/v3.5.0/docs/contribution/deprecated-features.md).
* [ ] affects platform compatibility, e.g. system version, browser version, platform sdk version, platform toolchain, language version, hardware compatibility etc.
* [ ] affects file structure of the build package or build configuration which requires user project upgrade.
* [ ] **introduces breaking changes**, please list all changes, affected features and the scope of violation.

### CODE REVIEW

File: native/cocos/2d/renderer/RenderDrawInfo.h [hunk 1]
```diff
@@ -256,7 +262,9 @@ class RenderDrawInfo final {
     struct DrawInfoAttrs {
         RenderDrawInfoType _drawInfoType{RenderDrawInfoType::COMP};
         bool _vertDirty{false};
-        bool _isMeshBuffer{false};
+        uint8_t _isMeshBuffer: 1;
+        uint8_t _isVertexPositionInWorld: 1;
+        uint8_t _padding: 6;
```
Comment (dumganhar) [inline native/cocos/2d/renderer/RenderDrawInfo.h:267]: Don't add a new boolean property, we could reuse the `byte` and make 8 bits for 8 boolean values.

**Comment by dumganhar** [comment]
@cocos-robot run test cases

**Review by qiuguohua — APPROVED** [review]
