### PR TITLE
 fix #17484: 修复tsx文件对象层自定义属性读取错误 

### LINKED ISSUE #17484: Tiled文件对象层属性读取错误
### Cocos Creator version

3.8.4

### System information

Windows10

### Issue description

[问题 1](https://github.com/cocos/cocos-engine/blob/fc7c067d14c1c2a452ea064bee2ea3d5497afc73/cocos/tiledmap/tmx-xml-parser.ts#L923)

```xml
<objectgroup id="2" name="Object">
   <properties>
     <property name="Start" type="bool" value="false"/>
   </properties>
   <object id="32" name="SavePoint" x="480" y="2040" width="120" height="120">
     <properties>
       <property name="Start" type="bool" value="true"/>
     </properties>
   </object>
</objectgroup>
```

在读取属性 property 时调用 `getElementsByTagName` 会得到所有后代节点中的匹配元素。因此，在读取 objectgroup 的 properties 节点时，如果子节点 object 也有 properties 节点，则会将 object 的 propertie 覆盖到 objectgroup 上，建议改为`querySelectorAll(':scope > properties')`。

[问题 2](https://github.com/cocos/cocos-engine/blob/fc7c067d14c1c2a452ea064bee2ea3d5497afc73/cocos/tiledmap/tmx-xml-parser.ts#L948C17-L948C32)
在读取 object 的 properties 时，会直接将 property 的值覆盖到 object 上。应将这些属性值存储在 properties 字段中，和其他地方保持一致。

### Relevant error log output

_No response_

### Steps to reproduce

_No response_

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by Jerry457**

### CODE REVIEW

File: cocos/tiledmap/tmx-xml-parser.ts [hunk 1]
```diff
@@ -818,7 +828,7 @@ export class TMXMapInfo {
 
         if (!imageLayer.sourceImage) {
             errorID(7221, source!);
-            console.warn(`Please try asset type of ${source} to 'sprite-frame'`);
+            // console.warn(`Please try asset type of ${source} to 'sprite-frame'`);
```
Comment (qiuguohua) [inline cocos/tiledmap/tmx-xml-parser.ts]: Suggest using 'warn' in cocos/core/platform/debug. ts

File: cocos/tiledmap/tmx-xml-parser.ts [hunk 2]
```diff
@@ -675,9 +685,9 @@ export class TMXMapInfo {
                                     tileset.imageName = shortName;
                                     tileset.sourceImage = this._spriteFrameMap![shortName];
                                     if (!tileset.sourceImage) {
-                                        console.error(`[error]: ${shortName} not find in [${Object.keys(this._spriteFrameMap!).join(', ')}]`);
+                                        // console.error(`[error]: ${shortName} not find in [${Object.keys(this._spriteFrameMap!).join(', ')}]`);
```
Comment (qiuguohua) [inline cocos/tiledmap/tmx-xml-parser.ts]: Suggest using 'error' from 'cocos/core/platform/debug.ts' instead

**Comment by qiuguohua** [comment]
@cocos-robot run test cases

**Comment by qiuguohua** [comment]
@cocos-robot run test cases

**Review by qiuguohua — APPROVED** [review]
