### PR TITLE
fixed #17876: [bug][Tween] callFunc before updateUntil may be invoked more than once.

### LINKED ISSUE #17876: updateUntil 会导致call执行2次
### Cocos Creator version

3.8.4

### System information

editor

### Issue description

-

### Relevant error log output

_No response_

### Steps to reproduce

```
import { _decorator, Component, log, tween } from 'cc';
const { ccclass } = _decorator;

@ccclass('Test.UpdateUntil')
export class Test_UpdateUntil extends Component {
    private testNumber = 0
    start() {
        this.startTestTween()
    }

    private startTestTween() {
        log("startTestTween")

        let ended  = false

        tween(this)
            .delay(1)
            .call(()=>{

                tween(this)
                    .delay(1)
                    .call(()=>{
                        ended = true
                    })
                    .start()

                this.testNumber++
                if(this.testNumber > 1) {
                    debugger
                }
            })
            //.delay(1)
            .updateUntil(()=>{
                return ended
            })
            .call(()=>{
                this.testNumber = 0

                this.scheduleOnce(()=>{
                    this.startTestTween()
                }, 0.3)
            })
            .start()
    }
}
```

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by dumganhar**
Re: #17876

### Changelog

*

-------

### Continuous Integration

This pull request:

* [ ] needs automatic test cases check.
  > Manual trigger with `@cocos-robot run test cases` afterward.
* [ ] does not change any runtime related code or build configuration
  > If any reviewer thinks the CI checks are needed, please uncheck this option, then close and reopen the issue.

-------

### Compatibility Check

This pull request:

* [ ] changes public API, and have ensured backward compatibility with [deprecated features](https://github.com/cocos/cocos-engine/blob/v3.5.0/docs/contribution/deprecated-features.md).
* [ ] affects platform compatibility, e.g. system version, browser version, platform sdk version, platform toolchain, language version, hardware compatibility etc.
* [ ] affects file structure of the build package or build configuration which requires user project upgrade.
* [ ] **introduces breaking changes**, please list all changes, affected features and the scope of violation.

### CODE REVIEW

File: cocos/tween/actions/action-interval.ts [hunk 1]
```diff
@@ -136,12 +136,16 @@ export abstract class ActionInterval extends FiniteTimeAction {
...
+        // NOTE: If the action's duration is unknown, the elapsed time should be kept at the point of the last frame,
         // because ActionUnknownDuration will be executed at each frame until its callback returns true.
         // After ActionUnknownDuration is finished, the isUnknownDuration method will return false
         // and the elapsed time will go as before.
         if (this.isUnknownDuration() && !this._firstTick) {
-            this._elapsed -= dt;
+            if (t < 1) {
+                this._elapsed -= dt;
+            } else {
+                this._elapsed = this._startTime + this._duration;
```
Comment (dumganhar) [inline cocos/tween/actions/action-interval.ts:147]: If t is 1, that indicates the current ActionInterval action is at the end, so its `_elapsed` should be `start time + duration`.

File: cocos/tween/actions/action-interval.ts [hunk 2]
```diff
@@ -113,8 +113,8 @@ export abstract class ActionInterval extends FiniteTimeAction {
         return true;
     }
 
-    isDone (): boolean {
-        return (this._elapsed >= this._duration);
+    override isDone (): boolean {
+        return this._elapsed >= this._duration && !this.isUnknownDuration();
```
Comment (dumganhar) [inline cocos/tween/actions/action-interval.ts:117]: If an action 's duration is unknown, we should not mark it as DONE until it isn't an `unknown duration` action.

**Review by minggo — APPROVED** [review]
