### PR TITLE
fixed #17162: Memory leak in WebSocket-okhttp.cpp

### LINKED ISSUE #17162: 提交个android调用websocket内存泄漏的错误 以及修改方案
### Cocos Creator version

3.8.0

### System information

Android

### Issue description

主要体现在websocket的传输后 内存泄漏问题。   cocos我感觉开源非常好，但是可编程渲染管线支持非常差。 特别是用js写代码还不能写线程 你要是用cpp写代码我立马抛弃unity    ，   毕竟以后dots为天下 希望支持dots时候改成cpp写代码

websocket 拿onbinarymessage。在android 的时候会有内存不断升高的bug，经过长时间的探究发现 需要在Websocket-okhttp.cpp的binarymessage里面加一句env->ReleaseByteArrayElements(static_cast<jbyteArray>(strongRef), array, 0);

### Relevant error log output

_No response_

### Steps to reproduce

image

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by dumganhar**
Re: #17162

### Changelog

*

-------

### Continuous Integration

This pull request:

* [ ] needs automatic test cases check.
  > Manual trigger with `@cocos-robot run test cases` afterward.
* [ ] does not change any runtime related code or build configuration
  > If any reviewer thinks the CI checks are needed, please uncheck this option, then close and reopen the issue.

-------

### Compatibility Check

This pull request:

* [ ] changes public API, and have ensured backward compatibility with [deprecated features](https://github.com/cocos/cocos-engine/blob/v3.5.0/docs/contribution/deprecated-features.md).
* [ ] affects platform compatibility, e.g. system version, browser version, platform sdk version, platform toolchain, language version, hardware compatibility etc.
* [ ] affects file structure of the build package or build configuration which requires user project upgrade.
* [ ] **introduces breaking changes**, please list all changes, affected features and the scope of violation.

### CODE REVIEW

File: native/cocos/network/WebSocket-okhttp.cpp [hunk 1]
```diff
@@ -389,6 +389,7 @@ JNI_PATH(nativeOnBinaryMessage)(JNIEnv *env,
         jboolean isCopy = JNI_FALSE;
         jbyte *array = env->GetByteArrayElements(static_cast<jbyteArray>(strongRef), &isCopy);
         wsOkHttp3->onBinaryMessage(reinterpret_cast<uint8_t *>(array), len);
+        env->ReleaseByteArrayElements(static_cast<jbyteArray>(strongRef), array, 0);
```
Comment (minggo) [inline native/cocos/network/WebSocket-okhttp.cpp]: I think can use JNI_ABORT here as don't have to copy data back to java.

Comment (dumganhar) [reply native/cocos/network/WebSocket-okhttp.cpp]: Fixed

**Review by minggo — APPROVED** [review]
