### PR TITLE
fixed #12625: The prototype chain for mesh.maxPosition is not Vec3 on version 3.6.0

### LINKED ISSUE #12625: [3.6.0] The prototype chain for mesh.maxPosition is not Vec3 on version 3.6.0 of the emulator
### Cocos Creator version

3.6.0

### System information

native app ｜ native pc

### Issue description

图片

### Relevant error log output

_No response_

### Steps to reproduce

图片

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by dumganhar**
Re: #12625

### Changelog

* fixed #12625: The prototype chain for mesh.maxPosition is not Vec3 on version 3.6.0

-------

### Continuous Integration

This pull request:

* [ ] needs automatic test cases check.
  > Manual trigger with `@cocos-robot run test cases` afterward.
* [ ] does not change any runtime related code or build configuration
  > If any reviewer thinks the CI checks are needed, please uncheck this option, then close and reopen the issue.

-------

### Compatibility Check

This pull request:

* [ ] changes public API, and have ensured backward compatibility with [deprecated features](https://github.com/cocos/cocos-engine/blob/v3.5.0/docs/contribution/deprecated-features.md).
* [ ] affects platform compatibility, e.g. system version, browser version, platform sdk version, platform toolchain, language version, hardware compatibility etc.
* [ ] affects file structure of the build package or build configuration which requires user project upgrade.
* [ ] **introduces breaking changes**, please list all changes, affected features and the scope of violation.

### CODE REVIEW

**Comment by dumganhar** [comment]
@cocos-robot run test cases

File: cocos/3d/framework/mesh-renderer.ts [hunk 1]
```diff
@@ -398,7 +398,8 @@ export class MeshRenderer extends ModelRenderer {
 
     public onGeometryChanged () {
         if (this._model && this._mesh) {
-            this._model.createBoundingShape(this._mesh.struct.minPosition, this._mesh.struct.maxPosition);
+            const meshStruct = this._mesh.struct;
```
Comment (PatriceJiang) [inline cocos/3d/framework/mesh-renderer.ts:401]: Is the purpose here to reduce temporary objects for GC?

Comment (dumganhar) [reply cocos/3d/framework/mesh-renderer.ts:401]: Yes, also a bit of tweak for performance since less property visit.

**Review by minggo — APPROVED** [review]

**Comment by dumganhar** [comment]
@cocos-robot run test cases

**Review by PatriceJiang — APPROVED** [review]

**Review by stanleyljl — APPROVED** [review]
