### PR TITLE
385 adapter the taobaominigame ClearLRU procedure 

### LINKED ISSUE #17040: taobao Platform can not trigger clearLRU
### Cocos Creator version

3.x

### System information

All Devices in Taobaominigam

### Issue description

taobao Platform can not trigger clearLRU.
in cache-manager function _cache,unzipAndCacheBundle, there is a mothed"isOutOfStorage" which will judge weather will trigger clearLRU, but in taobaominigame the right error  regular expression is "outOfStorageRegExp = /10028/; "
so in xxx\cocos\editors\Creator\2.4.12\resources\builtin\adapters\platforms\taobao-minigame\wrapper\fs-utils.js, the code var outOfStorageRegExp = /the maximum size of the file storage/;
will change to var outOfStorageRegExp = /10028/;

### Relevant error log output

_No response_

### Steps to reproduce

when cache is out of memory, will cause this issue

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by tangkaikk**
Re: #

### Changelog

*
Fixes https://github.com/cocos/cocos-engine/issues/17040 : taobao Platform can not trigger clearLRU
-------

### Continuous Integration

This pull request:

* [ ] needs automatic test cases check.
  > Manual trigger with `@cocos-robot run test cases` afterward.
* [ ] does not change any runtime related code or build configuration
  > If any reviewer thinks the CI checks are needed, please uncheck this option, then close and reopen the issue.

-------

### Compatibility Check

This pull request:

* [ ] changes public API, and have ensured backward compatibility with [deprecated features](https://github.com/cocos/cocos-engine/blob/v3.5.0/docs/contribution/deprecated-features.md).
* [ ] affects platform compatibility, e.g. system version, browser version, platform sdk version, platform toolchain, language version, hardware compatibility etc.
* [ ] affects file structure of the build package or build configuration which requires user project upgrade.
* [ ] **introduces breaking changes**, please list all changes, affected features and the scope of violation.

### CODE REVIEW

File: platforms/minigame/common/engine/cache-manager.js [hunk 1]
```diff
@@ -183,10 +183,13 @@ var cacheManager = {
         caches.sort(function (a, b) {
             return a.lastTime - b.lastTime;
         });
-        caches.length = Math.floor(caches.length / 3);
-        if (caches.length === 0) {
-            cleaning = false;
-            return;
+        let clearCachCount = Math.floor(caches.length / 3);
+        // 大于3则清理1/3， 小于等于3则全部清理
+        if(clearCachCount > 3){
```
Comment (zhefengzhang) [inline platforms/minigame/common/engine/cache-manager.js]: You can use caches.length >= 12 instead of clearCacheCount > 3.

And below, you can use caches.length < 3 instead of clearCacheCount === 0.

This way, when caches.length < 3, you won't need to execute Math.floor(caches.length / 3).

可以使用 caches.length >= 12 代替 clearCacheCount > 3

下面可以使用  caches.length < 3 代替 clearCachCount === 0

这样可以使得当 caches.length < 3 时不用执行 Math.floor(caches.length / 3)

Comment (tangkaikk) [reply platforms/minigame/common/engine/cache-manager.js]: change to : 
        if(caches.length < 3){
            console.warn("Due to caching large files in the game, there is insufficient storage space. Now starting forced cleaning.");
        }
        else{
            caches.length = Math.floor(caches.length / 3);
        }

File: platforms/minigame/common/engine/cache-manager.js [hunk 2]
```diff
@@ -183,10 +183,12 @@ var cacheManager = {
         caches.sort(function (a, b) {
             return a.lastTime - b.lastTime;
         });
-        caches.length = Math.floor(caches.length / 3);
-        if (caches.length === 0) {
-            cleaning = false;
-            return;
+        // 大于3则清理1/3， 小于等于3则全部清理
```
Comment (bofeng-song) [inline platforms/minigame/common/engine/cache-manager.js]: Please use english

Comment (tangkaikk) [reply platforms/minigame/common/engine/cache-manager.js]: have changed to English

File: platforms/minigame/common/engine/cache-manager.js [hunk 3]
```diff
@@ -183,10 +183,12 @@ var cacheManager = {
         caches.sort(function (a, b) {
             return a.lastTime - b.lastTime;
         });
-        caches.length = Math.floor(caches.length / 3);
-        if (caches.length === 0) {
-            cleaning = false;
-            return;
+        // cache length above 3 then clear 1/3， or clear all caches
+        if(caches.length < 3){
```
Comment (zhefengzhang) [inline platforms/minigame/common/engine/cache-manager.js]: Please maintain the same JavaScript formatting style as the original code, including leaving a space after if or else.

请保持与原代码一样的 js 排版格式，if 或 else 后面保留一个空格

Comment (tangkaikk) [reply platforms/minigame/common/engine/cache-manager.js]: The code has been formatted.

**Review by bofeng-song — APPROVED** [review]

File: platforms/minigame/platforms/taobao-mini-game/wrapper/fs-utils.js [hunk 4]
```diff
@@ -23,14 +23,14 @@
  THE SOFTWARE.
  ****************************************************************************/
 const fs = my.getFileSystemManager ? my.getFileSystemManager() : null;
-const outOfStorageRegExp = /the maximum size of the file storage/;  // not exactly right
+const outOfStorageRegExp = "10028";  // not exactly right
```
Comment (minggo) [inline platforms/minigame/platforms/taobao-mini-game/wrapper/fs-utils.js]: Why use string here?

File: platforms/minigame/platforms/taobao-mini-game/wrapper/fs-utils.js [hunk 5]
```diff
@@ -23,14 +23,14 @@
...
 
 const fsUtils = {
 
     fs,
 
-    isOutOfStorage (errMsg) {
-        return outOfStorageRegExp.test(errMsg);
+    isOutOfStorage (errorCode) {
+        return errorCode.toString() == outOfStorageRegExp;
```
Comment (minggo) [inline platforms/minigame/platforms/taobao-mini-game/wrapper/fs-utils.js]: It is wired to compare string content to check out of storage.

Comment (tangkaikk) [reply platforms/minigame/platforms/taobao-mini-game/wrapper/fs-utils.js]: taobao use errorCode "10028" to judge out of storage.

File: platforms/minigame/platforms/taobao-mini-game/wrapper/fs-utils.js (hunk 4 above)
Comment (tangkaikk) [reply platforms/minigame/platforms/taobao-mini-game/wrapper/fs-utils.js]: taobao error code is "10028"

File: platforms/minigame/platforms/taobao-mini-game/wrapper/fs-utils.js (hunk 5 above)
Comment (minggo) [reply platforms/minigame/platforms/taobao-mini-game/wrapper/fs-utils.js]: What's the type of errorCode?

Comment (tangkaikk) [reply platforms/minigame/platforms/taobao-mini-game/wrapper/fs-utils.js]: normally it is string

Comment (minggo) [reply platforms/minigame/platforms/taobao-mini-game/wrapper/fs-utils.js]: If so, why need to change to string?

Comment (tangkaikk) [reply platforms/minigame/platforms/taobao-mini-game/wrapper/fs-utils.js]: In case of the error code in the other apis like donwloadFile or copyFile which will trigger LRU in the feature, will be not string type.

Comment (minggo) [reply platforms/minigame/platforms/taobao-mini-game/wrapper/fs-utils.js]: - as the type is not fixed, so it is better to do some logic to make it more cearly
- please use `===` instead
- i think `outOfStorageRegExp` is not accurate, may be `outOfStorageErrorCode`

Comment (tangkaikk) [reply platforms/minigame/platforms/taobao-mini-game/wrapper/fs-utils.js]: I has changed the code as what you suggested.

**Review by minggo — APPROVED** [review]

**Review by zhefengzhang — APPROVED** [review]
