### PR TITLE
Component activation/inactivation should resume/pause animation

### LINKED ISSUE #11507: Animations keep running even the component has been inactivated
### Cocos Creator version

3.5.0

### System information

Windows 11

### Issue description

Transferred from https://forum.cocos.org/t/topic/136699

### Relevant error log output

_No response_

### Steps to reproduce

See the project attachment.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by shrinktofit**
This resolves #11507 .

### Changelog

* Activation/Inactivation of skeletal animation component should resume/pause animation.

This has been always holding for `Animation` but not for `SkeletonAnimation`.  Now just fix it.

-------

### Continuous Integration

This pull request:

* [x] needs automatic test cases check.

  > Manual trigger with `@cocos-robot run test cases` afterward.

-------

### Compatibility Check

This pull request:

* [ ] changes public API, and have ensured backward compatibility with [deprecated features](https://github.com/cocos/cocos-engine/blob/v3.5.0/docs/contribution/deprecated-features.md).
* [ ] affects platform compatibility, e.g. system version, browser version, platform sdk version, platform toolchain, language version, hardware compatibility etc.
* [ ] affects file structure of the build package or build configuration which requires user project upgrade.
* [ ] **introduces breaking changes**, please list all changes, affected features and the scope of violation.

### CODE REVIEW

**Comment by shrinktofit** [comment]
@cocos-robot run test cases

**Comment by shrinktofit** [comment]
@cocos-robot run test cases

File: cocos/3d/skeletal-animation/skeletal-animation.ts [hunk 1]
```diff
@@ -185,6 +185,16 @@ export class SkeletalAnimation extends Animation {
         this._removeAllUsers();
```
Comment (pandamicro) [inline cocos/3d/skeletal-animation/skeletal-animation.ts:185]: Shouldn't `onDestroy` stop all playing states and remove from the animation manager

Comment (shrinktofit) [reply cocos/3d/skeletal-animation/skeletal-animation.ts:185]: Yes it does: https://github.com/cocos/cocos-engine/blob/develop/cocos/3d/skeletal-animation/skeletal-animation.ts#L183 , https://github.com/cocos/cocos-engine/blob/develop/cocos/core/animation/animation-component.ts#L197

**Comment by suqionglian** [comment]
@cocos-robot run test cases

**Review by pandamicro — APPROVED** [review]

**Review by SantyWang — APPROVED** [review]
