### PR TITLE
fixed #16594: getComponent() can't support abstract class.

### LINKED ISSUE #16594: getComponent() can't support   abstract class.
### Cocos Creator version

3.8.1

### System information

all

### Issue description

getComponent() can't support   abstract class.

2.4.x has support this feature.

### Relevant error log output

_No response_

### Steps to reproduce

` node.getComponent(OneAbstractClass)` ,  vscode reports error message.

### Minimal reproduction project

_No response_

### PR DESCRIPTION
**Pull request by dumganhar**
Update ccbuild to 2.2.10,

Re: #16594

https://github.com/cocos/cocos-ccbuild/pull/63

### Changelog

*

-------

### Continuous Integration

This pull request:

* [ ] needs automatic test cases check.
  > Manual trigger with `@cocos-robot run test cases` afterward.
* [ ] does not change any runtime related code or build configuration
  > If any reviewer thinks the CI checks are needed, please uncheck this option, then close and reopen the issue.

-------

### Compatibility Check

This pull request:

* [ ] changes public API, and have ensured backward compatibility with [deprecated features](https://github.com/cocos/cocos-engine/blob/v3.5.0/docs/contribution/deprecated-features.md).
* [ ] affects platform compatibility, e.g. system version, browser version, platform sdk version, platform toolchain, language version, hardware compatibility etc.
* [ ] affects file structure of the build package or build configuration which requires user project upgrade.
* [ ] **introduces breaking changes**, please list all changes, affected features and the scope of violation.

### CODE REVIEW

**Review by minggo — APPROVED** [review]

File: cocos/core/value-types/bitmask.ts [hunk 1]
```diff
@@ -95,7 +95,7 @@ export function BitMask<T> (obj: T): T {
  * @returns @en True if it is a BitMask, false else.
  * @zh 如果是 BitMask，返回 true；否则返回 false。
  */
-BitMask.isBitMask = (BitMaskType): any => BitMaskType && BitMaskType.hasOwnProperty('__bitmask__');
+BitMask.isBitMask = (BitMaskType): any => BitMaskType && Object.prototype.hasOwnProperty.call(BitMaskType, '__bitmask__');
```
Comment (minggo) [inline cocos/core/value-types/bitmask.ts:98]: Why change it?

Comment (dumganhar) [reply cocos/core/value-types/bitmask.ts:98]: Fix an ESLint error:

> Do not access Object.prototype method 'hasOwnProperty' from target object.eslint[no-prototype-builtins](https://eslint.org/docs/latest/rules/no-prototype-builtins)


ESLint doesn't suggest to use obj.hasOwnProperty on target object since target object may contain a same key `hasOwnProperty` to override the original behavior.

File: cocos/core/value-types/enum.ts [hunk 2]
```diff
@@ -115,17 +117,17 @@ interface EnumExtras<EnumT> {
...
+function assertIsEnum <EnumT extends object> (enumType: EnumT): asserts enumType is EnumT & EnumExtras<EnumT> {
+    assertIsTrue(hasOwnPropertyProto.call(enumType, '__enums__'));
 }
 
 /**
  * Get the enumerators from the enum type.
  * @param enumType @en An enum type. @zh 枚举类型。
  */
-Enum.getList = <EnumT extends {}>(enumType: EnumT): readonly Enum.Enumerator<EnumT>[] => {
+Enum.getList = <EnumT extends object>(enumType: EnumT): readonly Enum.Enumerator<EnumT>[] => {
```
Comment (dumganhar) [inline cocos/core/value-types/enum.ts:130]: Fix an eslint error:

> Don't use `{}` as a type. `{}` actually means "any non-nullish value".
> - If you want a type meaning "any object", you probably want `object` instead.
> - If you want a type meaning "any value", you probably want `unknown` instead.
> - If you want a type meaning "empty object", you probably want `Record<string, never>` instead.
> - If you really want a type meaning "any non-nullish value", you probably want `NonNullable<unknown>` instead.eslint[@typescript-eslint/ban-types](https://typescript-eslint.io/rules/ban-types)

**Review by minggo — APPROVED** [review]

**Comment by dumganhar** [comment]
@cocos-robot run test cases

File: package-lock.json [hunk 3]
```diff
@@ -17626,9 +17583,9 @@
       "dev": true
     },
     "node_modules/typescript": {
-      "version": "4.3.5",
-      "resolved": "https://registry.npmjs.org/typescript/-/typescript-4.3.5.tgz",
-      "integrity": "sha512-DqQgihaQ9cUrskJo9kIyW/+g0Vxsk8cDtZ52a3NGh0YNTfpUSArXSohyUGnvbPazEPLu398C0UxmKSOrPumUzA==",
+      "version": "4.9.5",
+      "resolved": "https://registry.npmjs.org/typescript/-/typescript-4.9.5.tgz",
+      "integrity": "sha512-1FXk9E2Hm+QzZQ7z+McJiHL4NW1F2EzMu9Nq9i3zAaGqibafqYwCVU6WyWAuyQRRzOlxou8xZSyXLEN8oKj24g==",
```
Comment (dumganhar) [inline package-lock.json:17588]: Upgrade the default typescript cause `typedoc` failed since we're using `typedoc v0.22.13` which depends on typescript <= 4.7.  Perhaps, we need to update typedoc version now.
